spring:
  profiles:
    active: local
  mail:
    # Google smtp  server
    host:  smtp.gmail.com
    port: 587
    username: poseania1358@gmail.com
    password: eshddhvbwotbfkkz
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:static/query/*.xml
